version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"  # проксирование порта 80 контейнера на порт 8080 хоста
    volumes:
      - ./ghost-site:/usr/share/nginx/html:ro  # монтируем директорию с HTML в директорию Nginx
    restart: always
